### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by ghost** [ConflictPE/Extropy#1]
`
PocketMine-Steadfast Crash Dump Sun Sep 3 08:32:55 UTC 2017

Error: Return value of pocketmine\nbt\NBT::getLong() must be of the type integer, string returned
File: /src/pocketmine/nbt/NBT
Line: 315
Type: notice

Code:
[306] 		}else{
[307] 			$this->buffer .= $this->endianness === self::BIG_ENDIAN ? Binary::writeInt($v) : Binary::writeLInt($v);
[308] 		}
[309] 	}
[310] 
[311] 	public function getLong(bool $network = false) : int{
[312] 		if($network){
[313] 			return Binary::readVarLong($this->buffer, $this->offset);
[314] 		}
[315] 		return $this->endianness === self::BIG_ENDIAN ? Binary::readLong($this->get(8)) : Binary::readLLong($this->get(8));
[316] 	}
[317] 
[318] 	public function putLong($v, bool $network = false){
[319] 		if($network){
[320] 			$this->buffer .= Binary::writeVarLong($v);
[321] 		}else{
[322] 			$this->buffer .= $this->endianness === self::BIG_ENDIAN ? Binary::writeLong($v) : Binary::writeLLong($v);
[323] 		}
[324] 	}
[325] 

Backtrace:
#0 /src/pocketmine/nbt/NBT(258): pocketmine\nbt\tag\LongTag->read(pocketmine\nbt\NBT object, boolean )
#1 /src/pocketmine/nbt/tag/Compound(112): pocketmine\nbt\NBT->readTag(boolean )
#2 /src/pocketmine/nbt/NBT(258): pocketmine\nbt\tag\Compound->read(pocketmine\nbt\NBT object, boolean )
#3 /src/pocketmine/nbt/tag/Compound(112): pocketmine\nbt\NBT->readTag(boolean )
#4 /src/pocketmine/nbt/NBT(258): pocketmine\nbt\tag\Compound->read(pocketmine\nbt\NBT object, boolean )
#5 /src/pocketmine/nbt/NBT(203): pocketmine\nbt\NBT->readTag(boolean )
#6 /src/pocketmine/nbt/NBT(214): pocketmine\nbt\NBT->read(string ......Data...hardcore....initialized....GameType.......generatorVersion.......SpawnX...>...SpawnY.......SpawnZ.......version..J....DayTime.......LastPlayed...]..BQ...RandomSeed...........SizeOnDisk...........Time......qE...generatorName..flat...generatorOptions.....LevelName..Lobbys...GameRules...)
#7 /src/pocketmine/level/format/generic/BaseLevelProvider(48): pocketmine\nbt\NBT->readCompressed(string ..........M.AN.0.E....AHp!.(U%.Qh*.H]L.....lS...i.q0.E.f..<.y.....L...b{."C..z.-9..-..9u..z.T..G..).x.1........7.#..1......................5..R.t4.Z.......%.6t...O.l.m.+.....'A....~=/....Q6...}....Lk....M......t....c..7..0.*...)
#8 /src/pocketmine/level/Level(306): pocketmine\level\format\generic\BaseLevelProvider->__construct(pocketmine\level\Level object, string /storage/emulated/legacy/G/worlds/world/)
#9 /src/pocketmine/Server(1089): pocketmine\level\Level->__construct(pocketmine\Server object, string world, string /storage/emulated/legacy/G/worlds/world/, string pocketmine\level\format\anvil\Anvil)
#10 /src/pocketmine/Server(1681): pocketmine\Server->loadLevel(string world)
#11 /src/pocketmine/PocketMine(459): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /storage/emulated/legacy/G/, string /storage/emulated/legacy/G/, string /storage/emulated/legacy/G/plugins/)

PocketMine-MP version: 1.5.1 #0 [Protocol 101; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.10.49-g1ae94df #1 SMP PREEMPT Tue Oct 18 20:01:12 IST 2016 armv7l
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Loaded plugins:
DevTools 1.12.1 by PocketMine Team for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6
TnTLauncher 1 by  for API(s) 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA6, 3.0.0-ALPHA7

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWXtz27gR/yqonJtTriIl6i22SsexfYlv/FAs5dL2lMlAJCjhTBIMAcpWMu5n7y4ASpQfmUt7
bf9oNIlFAIt9/Haxu6A+1xRPWM33eq1utz3oDXqNWkylOslzkdf8zzW1yWC5lgrFA1Zr1BImJV3i
1BVTRZ6SNY0LRkREMhFcM5XwlM3n6ULN5xcvZ76/ZOpMpMv6c5IUUpGFJlUrRpAx4aliS5Y3iFQ5
T5ck1zxZCIKiIo5/5DFKakolchDaZEkRU8XCZsyWNNg0XzVlHjR3gpsgtwli3WyVIYty+6NEQBDD
sOZ3PDBa5RTs83+pHbTIExvq7d7wuf/QTkWX8zkaOaNL50XOaFh/DAsiFr+yQDXIQoiY0ZQ8Bw0O
vEelAcvmkUgyUaRh3fPaj4kFlkYaiK3v8Wz/SxaU8r7ahM5/wITuf9eE3tPiWp2v07z/NCuv+0VW
dXsIXP05porC14rmYSByhlM85YrTmH9iIQ5f0YTN4BQZenfJUpZTOCk/s1xykdrpaUZv0r/Cw4ty
8Lfqyt/tYF1u+skI38wgL9i1M0gIk5hutNj3rvvyDXxf0TQUyZQZXUqWoNtleszldWVyx+njSVXP
C4rzEZzo6uxlpkAPaQSzNYsN2ZlYLDbSWn1VxAyfNeCDB4DHuK0ZiTyhqqkZ86D5kkqm+U1yseYh
y+vd4RfdgcGUQ7Zj9xyDn3P38MJtuWiOe/g6+4Nbf/ud+2b1g/v6/ZkmiKfoL/cj0kSu+2d3YwyC
/4vP7rx25LqfXGfkuo7rjgoczMA0sMi9db1SysA9cHej/U8PPOCqrlv67zu3jzBeurGbuH/UU98f
4t9/jJv49aYPf+60DtfGAv3BPW6AosCcH0pIh09AqvGrd1r9e8Dp1fncID6fW8jn8weYOy8+fAjA
uyovAlV/hIWm3p5Ri/sX8v+NyONQmq+m1n30QPcpyyG6615rOHpcby30adXM/vtKaZFfreJ2wxfg
o+maw/AQv0yNaD1pU3/o3bPJrDgvYkFD46+qwobfw6Iz0Y/n8Fjv9kZPsHwKIDwpVPFFzI6gd5Bn
ILmCV5WyUDyW8/k55emZWC4fovoFHH8vmiwuljyVEC3v7xo19r9vdH5zlwLqGuVrfkRjyRq1QIQM
lYcjCSzmaq7uGCx8hl2d1sBOzdUzteLSebEoogggd8fETrA05DRNwVIyHo+JZHHk+y9PX304uTg+
PbwgfyEveUrzje/f5Fyx01TVn62fE39/+szO/0lLHZaK6NFIj/Sz14Jn/eDpyaxYxDwgUZEGmPFJ
CSBWU/IsZQoC9pqMiTYVhQKG2jCvbUXwqF7SPTcrna3JBuCtopjQf6a5FrCHRqPEQkSRZMoY4XWr
Rng9O7I8vxo8FF6VDJbWh8+rOGqKR0iMNv0KiIMSxOGjIGaFAfHZ2nQ4D4E0QI2egrDdejpq9ry+
RdM6vu09iMB2+/eOwFLigxDcV6VTdV+7u4Ovja6s3X1r97+1+9/a/W/t/rd2/1u7/63d/79p9xs1
k3ZibJltBoR+wIPT5QFQi4LHYc1vQZedCyUCAXRey2vUaMY1mdd2W0C35AqGrd/4gQ05vY75Ave4
Q82hSCm+dK2d8bS4JbEIaLwScGnouF7L7Y6cpUfZqBtGBPqF6fmETK5OTs4nMzKDC8hloIg3JO2W
3/J8r01OpzMYeH1C82Q9iIE7vvz0awM44R0YfYIWC4YdGLbM4gchS9kwoQeQ3HPBw9r2hiERomO2
nkGt089W4+1UYw9AQAYRpIVaiVxiX7WLMDJjNEHwNYy/1NpWE62Rc3g2eX3o7Q/b+8PO/rC7P+zt
D/soiaUUohPMhuCFW1LIMgAB1YI1KSJ1XJ1IKF6otpbN5xUb8VTB2nR2eDV7O4GJG7aQ0G/C3Eqp
TPrNJkTDqli4gUgqp6q55QGIztLZGYUGfcXyCpLV2QqYXhXFHWidfxO0/v5wsIeSvUz+JphAbXOg
d+hMLqezd5dXZ8dVfNIiju8wnGgO9ipW2iN1cnHhhGUsV5xh9B1MtiNyJNKILwleiuf5PD2YFimZ
sox0SGvod9p+r0Pezo4w4ge4nggVjhHxIKeR8snkhJj0hYtGlpOJXI29kddp6x0sEfnGiXnC1bjd
65/j5M0KlIY5qcZwD9R7sVtyMBEwfbMae329m946GfZGuRy3WzhD41jcOFHMl6t7m2nKE0B2LFJN
Z0ZWcGtHlohFSYOPVYIlRW1DZkZQMALmbOesrLJjLMfZOrPcQh5FPChitRl7mlvZczlw0VWQNuUY
p3U5cjAqx7pm7OYkdHsVEnyRMT4++fHw7dkMZ038OB8Llm+sSDuVQ+Eo9cFnN4M6AczD8Q/6A2gU
SjiSrlmJDo6tgltTcN2i7YTQH5fz+JOVU2ShJtXbMbFt6467SWKMKoJhSgIdUAXwxfsxxhUBIMnu
rDpTCHWINDJbMclIiQ3kU6bf3wi4ncIDVSSAm6rQr3Z4GsRFyEJ4IA8iGnlNRVK+ALrPU9KINYiA
lVwiS7KA9vOabESRW16ERwRczCOuJYB3cwjCeDNPMaYNK38OkleFCgWGkHlX5ZN5zXYvQSygk53X
gOrgECOUYHDrTsTkd7LmlLxB1wGJdqFjV3yCWRM3TlewjyKCEm48xEohNyuWwrQhJ4UEeCB1gIpY
eMnh5BQoIYOFAERlwQG1FqDUjv2JDpaSD5QggnFMAEjwEqq62MD+iEIEA7kNre3qlg8N1zQNQEBA
IZlup4sszRzw9A2cD02us5w2C5MayBPpJhGFhB4CYgPACcDNggTgDcXALDQ1Z5g80BAJm5zCoFwa
cFEkC+xpInIoN2kwo/Ia265rcCwuvzu8uji9eOVDYHFJbngcozOBPUTEMhYLGhOTjIwwuKMWinAF
LNLvdZShy0yM6feIQtHYRYNRmGMF+cTDsAjZolhiTBycRuQF8RqaEYqU6ES9XDpQlhytY2GXPuCa
VekWiT0VVQVaArUtAfdsI2OXH3axeACnp/QWMa2tOTSa1JoPsWKix4Ac6gDRWxyzxScJLC3hpFpT
dAFHRSF6lCRRLhIIvSp/gBYPpaqIBy+qh9rA6ceCpR13OTuxboF/QQHnK4XzpRnxJItZAmOtnpW8
Vc8G0RzqdpFeOxgVGFz6mEEwpQqjQa9JDBmti60XBNIDgSi7BmJ4dPDRQl7ePTFDabwQqdBAZUVY
pi55DYUGGI0hQ8BhOZq8bcAWKckCPHTDQ7Uy0WTcVnJ1rIOHTytKc3yVQhgcIqsx0GK5M0Q+gVq5
MxyVLw0/p7eE3ucJ5zTQt2nD8YHdLdx5RUMOB3C3yypBrQbak2Ynfjm5pvdJ9+ucqGuzLRhylwiC
mFGjjq78D5xryxHAp818t2KYs1GnvDAHaEeB0UUJVlyWa7ev8J0CgUIjDCm2T3YWmb3a7dQnA087
enEZcxWsNo/sMulBE8d0qb2PjN5KDA5lMgw4P6Jwj9hWeg0NJGA4wBBGGgw8Vbbza9hjEnKTuivm
WP0TugG9oDqZRDXX6d7RCaiSUCEA3IcRADiVBX0b+lD3UnARFuBHGO2diq0XAt8scRE6PNUE4MR+
q4U0euTAKhKZFsvRbRVGCZIAUHCHBcblLB447DawudBskEiXDgcDIi0yn4wMc9Of6X5M57iSF3AZ
4C4rEJn2cHhDUdB2Us/RZMEhIAyJ7XNMVfHLWgTZkMpVWWs0OPb0gGu3lS/c4aRrEf70sy1Femab
jvdm4cLHoXXc7cabpm9kupWmKWVKKxhzqE8mpZ/cUjxHZoB1BMLFXlR8Yh/0EkAJF3AA7hfdskFL
jDdzkb1HjuaFiK+bNHarWIrb9J3yCGK4clPF41kZZsHeqvwIR4N19C164IRsjXdbc60uSRYB5OhV
ZQLu1QABzatT9ne+7bjI48oQegvFqvSRql6ml2F1kFSXVoCnvgvjNe1XaS/GXT1MFuY9RYUc6twm
U5WJ6eRsz3jIZVXrFUVDquIzIfltdWzOrNSXfc/Fe/EVi2JzfamyWiWiqrjUMSCrum0AbP3WwD6R
Hqx4bUSdOHj36rW6rQE8PjvFsOyN2GLQH0TMG9B+fzDqDUeLXtAa9MNRRIfDsBN2oQi0yDPgPVlp
d+BLALyxKnHNUv5pD/J3kHByFmlPdzTVhuqOXr85uDoaoOd5Zl48dAzAqCff8ri7+yfvcuU6
===END CRASH DUMP===
`

commit: ebf67eb

**Comment by JackNoordhuis** [comment]
I cannot reproduce this issue on any of our servers, due to it not affecting our servers I will not be spending any more time looking into the issue.

If you can provide steps to reproduce this I will get it fixed.
